# Idempotent `git apply` helper, used as a FetchContent/ExternalProject PATCH_COMMAND.
#
# Usage:
#   ${CMAKE_COMMAND} -DPATCH_FILE=<abs path> -P <this file>
#
# Runs with the freshly-populated dependency source dir as its working directory
# (ExternalProject's patch step sets WORKING_DIRECTORY to SOURCE_DIR, and
# `cmake -P` inherits it), so a patch generated by `git diff` from that same
# repo root applies with plain `git apply`.
#
# Why the guard: `git apply` is not idempotent — re-running it on an
# already-patched tree fails. CMake normally runs the patch step only on a fresh
# population, but a changed GIT_TAG or a hand-touched stamp can re-run it, and a
# hard error there is a confusing way to find that out. `git apply --reverse
# --check` exits 0 exactly when the patch is already applied, so use it to skip.

if(NOT DEFINED PATCH_FILE)
    message(FATAL_ERROR "apply_patch.cmake: PATCH_FILE not set")
endif()
if(NOT EXISTS "${PATCH_FILE}")
    message(FATAL_ERROR "apply_patch.cmake: patch file not found: ${PATCH_FILE}")
endif()

find_package(Git REQUIRED)

execute_process(
    COMMAND "${GIT_EXECUTABLE}" apply --reverse --check --ignore-whitespace "${PATCH_FILE}"
    RESULT_VARIABLE _already_applied
    OUTPUT_QUIET ERROR_QUIET)

if(_already_applied EQUAL 0)
    message(STATUS "apply_patch: already applied, skipping: ${PATCH_FILE}")
    return()
endif()

execute_process(
    COMMAND "${GIT_EXECUTABLE}" apply --ignore-whitespace "${PATCH_FILE}"
    RESULT_VARIABLE _result
    ERROR_VARIABLE  _stderr)

if(NOT _result EQUAL 0)
    message(FATAL_ERROR "apply_patch: failed to apply ${PATCH_FILE}\n${_stderr}")
endif()

message(STATUS "apply_patch: applied ${PATCH_FILE}")
